componentNames:
  request:
    class: Delta_HttpRequest

  response:
    class: Delta_HttpResponse

  session:
    class: Delta_HttpSession

  user:
    class: Delta_AuthorityUser

  view:
    class: Delta_WebView
