sanitizer:
  whitespace:
    class: Delta_WhitespaceSanitizer

  emoji:
    class: Delta_EmojiSanitizer

  multibyteKana:
    class: Delta_MultibyteKanaSanitizer

  vendorCharacter:
    class: Delta_VendorCharacterSanitizer

validators:
  required:
    class: Delta_RequiredValidator
    requiredError: '{$label}が未指定です。'

  length:
    class: Delta_LengthValidator
    minLengthError: '{$label}は{$minLength}文字以上入力して下さい。'
    maxLengthError: '{$label}は{$maxLength}文字以内で入力して下さい。'
    matchLengthError: '{$label}は{$matchLength}文字で入力して下さい。'

  radio:
    class: Delta_RadioValidator
    requiredError: '{$label}が未指定です。'

  check:
    class: Delta_CheckValidator
    requiredMatchError: '{$label}は{$requiredMatch}つにチェックを付けて下さい。'
    requiredMinError: '{$label}は{$requiredMin}つ以上にチェックを付けて下さい。'
    requiredMaxError: '{$label}は{$requiredMax}つ以内でチェックを付けて下さい。'

  select:
    class: Delta_SelectValidator
    requiredMatchError: '{$label}は{$requiredMatch}つにチェックを付けて下さい。'
    requiredMinError: '{$label}は{$requiredMin}つ以上にチェックを付けて下さい。'
    requiredMaxError: '{$label}は{$requiredMax}つ以内でチェックを付けて下さい。'

  textarea:
    class: Delta_TextareaValidator
    matchRowSizeError: '{$label}は{$matchRowSize}行で指定して下さい。'
    minRowSizeError: '{$label}は{$minRowSize}行以上で指定して下さい。'
    maxRowSizeError: '{$label}は{$maxRowSize}行以下で指定して下さい。'

  email:
    class: Delta_EMailValidator
    formatError: '{$label}の書式が正しくありません。'

  string:
    class: Delta_StringValidator
    formatError: '{$label}に許可されない文字が含まれています。'

  multibyte:
    class: Delta_MultibyteValidator
    multibyteError: '{$label}は全角文字で指定して下さい。'
    hiraganaError: '{$label}は全角ひらがなで指定して下さい。'
    katakanaError: '{$label}は全角カタカナで指定して下さい。'

  vendorCharacter:
    class: Delta_VendorCharacterValidator
    formatError: '{$label}に使用できない文字が含まれています。'

  numeric:
    class: Delta_NumericValidator
    formatError: '{$label}の書式が不正です。'
    floatError: '{$label}は小数点以下を指定することはできません。'

  range:
    class: Delta_RangeValidator
    rangeError: '{$label}は{$min}〜{$max}の間で指定して下さい。'
    floatError: '{$label}は小数点以下を指定することはできません。'

  mask:
    class: Delta_MaskValidator
    formatError: '{$label}の書式が不正です。'

  compare:
    class: Delta_CompareValidator
    matchError: '{$compareLabel}が一致していません。'

  date:
    class: Delta_DateValidator
    formatError: '{$label}の書式が不正です。'
    allowError: '{$label}に無効な日付が指定されています。'

  zipCode:
    class: Delta_ZipCodeValidator
    formatError: '{$label}の書式が不正です。'

  url:
    class: Delta_URLValidator
    formatError: '{$label}の書式が不正です。'
    httpError: '{$label}はhttps://〜形式で指定して下さい。'
    httpsError: '{$label}はhttp://〜形式で指定して下さい。'

  ipAddress:
    class: Delta_IPAddressValidator
    formatError: '{$label}の書式が不正です。'
    notAllowError: '{$label}に許可されないアドレスが指定されています。'

  domain:
    class: Delta_DomainValidator
    formatError: '{$label}の書式が不正です。'

  sequenceString:
    class: Delta_SequenceStringValidator
    sizeError: '{$label}は同じ文字が{$size}文字以上連続しています。'

  fileUpload:
    class: Delta_FileUploadValidator
    encodeError: '{$label}のエンコード形式が不正です。'
    unuploadError: '{$label}がアップロードされていません。'
    partialError: '{$label}ファイルのアップロード中に欠損が発生しました。'
    temporaryError: 'アップロードファイルを配置するテンポラリディレクトリが存在しません。'
    writeError: 'アップロードファイルの書き込みに失敗しました。'
    extensionModuleError: '拡張モジュールによりアップロードが中止されました。'
    minSizeError: '{$label}のファイルサイズが小さすぎます。{$minSize}以上のファイルをアップロードして下さい。'
    maxSizeError: '{$label}のファイルサイズが大きすぎます。{$maxSize}以下のファイルをアップロードして下さい。'
    mimeTypeError: '{$label}に指定されたファイル形式は許可されていません。'
    extensionError: '{$label}に指定されたファイル拡張子は許可されていません。'

  phoneNumber:
    class: Delta_PhoneNumberValidator
    formatError: '{$label}の形式が不正です。'

  zipCode:
    class: Delta_ZipCodeValidator
    formatError: '{$label}の形式が不正です。'

  creditCard:
    class: Delta_CreditCardValidator
    unsupportedCardError: '指定されたクレジットカードはサポートされていません。'
    denyCardError: '許可されないクレジットカードです。'
    formatError: 'クレジットカード番号の形式が正しくありません。'
    checkDigitError: 'クレジットカード番号が不正です。'
