rewriteTestRoute:
  uri: /rewriteTest
  forward:
    module: entry
    controller: Index
    action: index

cpanelConnectTestRoute:
  uri: /cpanel/:controller/:action
  forward:
    module: cpanel

defaultRoute:
  uri: /:action
  forward:
    module: "{%MODULE.ENTRY%}"
    controller: Index

moduleRoute:
  uri: /:module/:controller/:action

rootRoute:
  uri: /
  forward:
    module: "{%MODULE.ENTRY%}"
    controller: Index
    action: index

