rewriteTestRoute:
  uri: /rewriteTest
  forward:
    module: entry
    controller: Index
    action: index

cpanelRoute:
  uri: /cpanel/:controller/:action
  forward:
    module: cpanel

moduleRoute:
  uri: /:module
  forward:
    controller: Index

controllerRoute:
  uri: /:module/:controller/:action

rootRoute:
  uri: /
  forward:
    module: entry
    controller: Index
    action: index
