rewriteTestRoute:
  uri: /rewriteTest
  forward:
    module: entry
    action: Index

cpanelConnectTestRoute:
  uri: /cpanel/connectTest
  forward:
    module: cpanel
    action: ConnectTest

defaultRoute:
  uri: /:action

moduleRoute:
  uri: /:module/:action

frontRoute:
  uri: /
  forward:
    module: "{%MODULE.ENTRY%}"
    action: Index

