rewriteTestRoute:
  uri: /rewriteTest
  forward:
    module: entry
    controller: Index
    action: index

cpanelRootRoute:
  uri: /cpanel/
  forward:
    module: cpanel

cpanelActionRoute:
  uri: /cpanel/:controller/:action
  forward:
    module: cpanel

moduleRoute:
  uri: /:module/
  forward:
    controller: Index

controllerRoute:
  uri: /:module/:action
  forward:
    controller: Index

actionRoute:
  uri: /:module/:controller/:action

rootRoute:
  uri: /
  forward:
    module: entry
    controller: Index
    action: index
