rewriteTestRoute:
  uri: /rewriteTest
  forward:
    module: entry
    action: Index

cpanelTestRoute:
  uri: /cpanelTest
  forward:
    module: cpanel
    action: ModuleConnectTest

defaultRoute:
  uri: /:action

moduleRoute:
  uri: /:module/:action

